version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm install -g npm
      - run: npm cache clean --force
      - run: npm install --no-package-lock
      - run: npm run build
      - run: npm run rebuild
      - run: npm run dist:win

      - store_artifacts:
          path: /Users/distiller/.npm/_logs/

      - store_test_results:
          path: /Users/distiller/.npm/_logs/

workflows:
  version: 2
  build:
    jobs:
      - build_windows