version: 2
jobs:
  build_macos:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: npm install
      - run: npm run rebuild
      - run: npm run dist:mac

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - store_artifacts:
          path: /Users/distiller/.npm/_logs/

      - store_test_results:
          path: /Users/distiller/.npm/_logs/

workflows:
  version: 2
  build:
    jobs:
      - build_macos